services:
  postgres:
    image: postgres:17
    ports:
      - "5432:5432"
    volumes:
      - postgres-vol:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=62bFiMfX<7+^
      - POSTGRES_USER=pgUser
      - POSTGRES_DB=HotelBookingDB

volumes:
  postgres-vol: